### ISSUE TITLE
Defining instruments in config file not working

### ISSUE THREAD

**Issue by fabianostermann** [fabianostermann/ArtificialSongGenerator#1]
When encommenting config line for `bass-instruments`, the instrument loader fails:

```
Config file 'dummy.conf' loaded.
Making music..
Exception in thread "main" java.lang.RuntimeException: The instrument 'Acoustic_Bass]' is not recognized
        at org.jfugue.pattern.Pattern.setInstrument(Pattern.java:339)
        at parts.SongPartElement.getPattern(Unknown Source)
        at parts.SongPart.getPattern(Unknown Source)
        at main.ArtificialSongGenerator.main(Unknown Source)
```

Using --print-instruments:
```
Bass:
- ElectricBass [28
- 55
- Scarbee_JayBass_Neck
- Electric_Bass_Finger]
- OrganBass [36
- 96
- SomeOrgan??
- Percussive_Organ]
- DoubleBassPizz [24
- 65
- Basses_SessionStringsPro
- Acoustic_Bass]
- DoubleBassArco [24
- 65
- Basses_SessionStringsPro
- Contrabass]
```

**Comment by fabianostermann** [comment]
Found the problem and fixed it (cc2aca7):

In `src/main/Config.java`: `parseConfigAndStore()`, we split the config strings at every DELIM (`,`).
Inserting a check for commas being outside of square brackets (ATTR_OPEN, ATTR_CLOSE) fixed it. I used regex lookahead filters (for now).

For clarification, explanation of the config syntax:
`
bass-instruments = <name> [<lowest_note>, <hightest_note>, <sampler_info>,<midi_instrument>], ...
`
- `<name>` defines the name for the output midi track file (`thesong_<name>.mid`) and how the instrument is referred to in the annotation files (`thesong_segments.arff` and `thesong_onsets.arff`).
- `<lowest/highest_note>` is the pitch range, that the generator will use. Necessary if realistic samplers, that have limited range, are to be used for synthesizing later.
- `<sampler_info>`: Used for conveniance, enables to print this information using `--print-instruments`.
- `<midi_instruments>`: The instrument used for demo playback and for the output midi files. 

If you want to use AGS **midi only**, use instrument names as defined in [jFugue midi dictionary](https://github.com/fabianostermann/ArtificialSongGenerator/blob/master/ASGLib/src/asglib/MidiDictionary.java), see `NSTRUMENT_STRING_TO_BYTE`. Lower case is allowed.

Example: `bass-instruments = acoustic_bass, electric_bass_pick, fretless_bass, tuba`
